# dstrings.py
#
# DESCRIPTION:
#       Global text strings used across the engine.

# -----------------------------------------------------------------------------
# HUD & CHAT STRINGS
# -----------------------------------------------------------------------------

HUSTR_PLRGREEN  = "PLAYER 1"
HUSTR_PLRINDIGO = "PLAYER 2"
HUSTR_PLRBROWN  = "PLAYER 3"
HUSTR_PLRRED    = "PLAYER 4"

HUSTR_MSGU = ""

HUSTR_TALKTOSELF1 = "YOU MUMBLE TO YOURSELF"
HUSTR_TALKTOSELF2 = "WHO'S THERE?"
HUSTR_TALKTOSELF3 = "YOU SWEAR YOU HEARD FOOTSTEPS"
HUSTR_TALKTOSELF4 = "YOU ARE GOING CRAZY"
HUSTR_TALKTOSELF5 = "YOU HAVE LOST YOUR MIND"

# -----------------------------------------------------------------------------
# DOOM 1 (SHAREWARE / ULTIMATE) LEVEL NAMES
# -----------------------------------------------------------------------------

HUSTR_E1M1 = "E1M1: Hangar"
HUSTR_E1M2 = "E1M2: Nuclear Plant"
HUSTR_E1M3 = "E1M3: Toxin Refinery"
HUSTR_E1M4 = "E1M4: Command Control"
HUSTR_E1M5 = "E1M5: Phobos Lab"
HUSTR_E1M6 = "E1M6: Central Processing"
HUSTR_E1M7 = "E1M7: Computer Station"
HUSTR_E1M8 = "E1M8: Phobos Anomaly"
HUSTR_E1M9 = "E1M9: Military Base"

HUSTR_E2M1 = "E2M1: Deimos Anomaly"
HUSTR_E2M2 = "E2M2: Containment Area"
HUSTR_E2M3 = "E2M3: Refinery"
HUSTR_E2M4 = "E2M4: Deimos Lab"
HUSTR_E2M5 = "E2M5: Command Center"
HUSTR_E2M6 = "E2M6: Halls of the Damned"
HUSTR_E2M7 = "E2M7: Spawning Vats"
HUSTR_E2M8 = "E2M8: Tower of Babel"
HUSTR_E2M9 = "E2M9: Fortress of Mystery"

HUSTR_E3M1 = "E3M1: Hell Keep"
HUSTR_E3M2 = "E3M2: Slough of Despair"
HUSTR_E3M3 = "E3M3: Pandemonium"
HUSTR_E3M4 = "E3M4: House of Pain"
HUSTR_E3M5 = "E3M5: Unholy Cathedral"
HUSTR_E3M6 = "E3M6: Mt. Erebus"
HUSTR_E3M7 = "E3M7: Limbo"
HUSTR_E3M8 = "E3M8: Dis"
HUSTR_E3M9 = "E3M9: Warrens"

HUSTR_E4M1 = "E4M1: Hell Beneath"
HUSTR_E4M2 = "E4M2: Perfect Hatred"
HUSTR_E4M3 = "E4M3: Sever the Wicked"
HUSTR_E4M4 = "E4M4: Unruly Evil"
HUSTR_E4M5 = "E4M5: They Will Repent"
HUSTR_E4M6 = "E4M6: Against Thee Wickedly"
HUSTR_E4M7 = "E4M7: And Hell Followed"
HUSTR_E4M8 = "E4M8: Unto the Cruel"
HUSTR_E4M9 = "E4M9: Fear"

# -----------------------------------------------------------------------------
# DOOM 2 LEVEL NAMES
# -----------------------------------------------------------------------------

HUSTR_1  = "MAP01: Entryway"
HUSTR_2  = "MAP02: Underhalls"
HUSTR_3  = "MAP03: The Gantlet"
HUSTR_4  = "MAP04: The Focus"
HUSTR_5  = "MAP05: The Waste Tunnels"
HUSTR_6  = "MAP06: The Crusher"
HUSTR_7  = "MAP07: Dead Simple"
HUSTR_8  = "MAP08: Tricks and Traps"
HUSTR_9  = "MAP09: The Pit"
HUSTR_10 = "MAP10: Refueling Base"
HUSTR_11 = "MAP11: 'O' of Destruction!"
HUSTR_12 = "MAP12: The Factory"
HUSTR_13 = "MAP13: Downtown"
HUSTR_14 = "MAP14: The Inmost Dens"
HUSTR_15 = "MAP15: Industrial Zone"
HUSTR_16 = "MAP16: Suburbs"
HUSTR_17 = "MAP17: Tenements"
HUSTR_18 = "MAP18: The Courtyard"
HUSTR_19 = "MAP19: The Citadel"
HUSTR_20 = "MAP20: Gotcha!"
HUSTR_21 = "MAP21: Nirvana"
HUSTR_22 = "MAP22: The Catacombs"
HUSTR_23 = "MAP23: Barrels o' Fun"
HUSTR_24 = "MAP24: The Chasm"
HUSTR_25 = "MAP25: Bloodfalls"
HUSTR_26 = "MAP26: The Abandoned Mines"
HUSTR_27 = "MAP27: Monster Condo"
HUSTR_28 = "MAP28: The Spirit World"
HUSTR_29 = "MAP29: The Living End"
HUSTR_30 = "MAP30: Icon of Sin"
HUSTR_31 = "MAP31: Wolfenstein"
HUSTR_32 = "MAP32: Grosse"

# -----------------------------------------------------------------------------
# PLUTONIA LEVEL NAMES
# -----------------------------------------------------------------------------

PHUSTR_1  = "MAP01: Congo"
PHUSTR_2  = "MAP02: Well of Ruin"
PHUSTR_3  = "MAP03: Aztec"
PHUSTR_4  = "MAP04: Caged"
PHUSTR_5  = "MAP05: Ghost Town"
PHUSTR_6  = "MAP06: Baron's Lair"
PHUSTR_7  = "MAP07: Caughtyard"
PHUSTR_8  = "MAP08: Realm"
PHUSTR_9  = "MAP09: Abattoire"
PHUSTR_10 = "MAP10: Onslaught"
PHUSTR_11 = "MAP11: Hunted"
PHUSTR_12 = "MAP12: Speed"
PHUSTR_13 = "MAP13: The Crypt"
PHUSTR_14 = "MAP14: Genesis"
PHUSTR_15 = "MAP15: The Twilight"
PHUSTR_16 = "MAP16: The Omen"
PHUSTR_17 = "MAP17: Compound"
PHUSTR_18 = "MAP18: Neurosphere"
PHUSTR_19 = "MAP19: NME"
PHUSTR_20 = "MAP20: The Death Domain"
PHUSTR_21 = "MAP21: Slayer"
PHUSTR_22 = "MAP22: Impossible Mission"
PHUSTR_23 = "MAP23: Tombstone"
PHUSTR_24 = "MAP24: The Final Frontier"
PHUSTR_25 = "MAP25: The Temple of Darkness"
PHUSTR_26 = "MAP26: Bunker"
PHUSTR_27 = "MAP27: Anti-Christ"
PHUSTR_28 = "MAP28: The Sewers"
PHUSTR_29 = "MAP29: Odyssey of Noises"
PHUSTR_30 = "MAP30: The Gateway of Hell"
PHUSTR_31 = "MAP31: Cyberden"
PHUSTR_32 = "MAP32: Go 2 It"

# -----------------------------------------------------------------------------
# TNT EVILUTION LEVEL NAMES
# -----------------------------------------------------------------------------

THUSTR_1  = "MAP01: System Control"
THUSTR_2  = "MAP02: Human Cargo"
THUSTR_3  = "MAP03: Power Control"
THUSTR_4  = "MAP04: Wormhole"
THUSTR_5  = "MAP05: Hanger"
THUSTR_6  = "MAP06: Open Season"
THUSTR_7  = "MAP07: Prison"
THUSTR_8  = "MAP08: Metal"
THUSTR_9  = "MAP09: Stronghold"
THUSTR_10 = "MAP10: Redemption"
THUSTR_11 = "MAP11: Storage Facility"
THUSTR_12 = "MAP12: Crater"
THUSTR_13 = "MAP13: Nukage Processing"
THUSTR_14 = "MAP14: Steel Works"
THUSTR_15 = "MAP15: Dead Zone"
THUSTR_16 = "MAP16: Deepest Reaches"
THUSTR_17 = "MAP17: Processing Area"
THUSTR_18 = "MAP18: Mill"
THUSTR_19 = "MAP19: Shipping/Respawning"
THUSTR_20 = "MAP20: Central Processing"
THUSTR_21 = "MAP21: Administration Center"
THUSTR_22 = "MAP22: Habitat"
THUSTR_23 = "MAP23: Lunar Mining Project"
THUSTR_24 = "MAP24: Quarry"
THUSTR_25 = "MAP25: Baron's Den"
THUSTR_26 = "MAP26: Ballistyx"
THUSTR_27 = "MAP27: Mount Pain"
THUSTR_28 = "MAP28: Heck"
THUSTR_29 = "MAP29: River Styx"
THUSTR_30 = "MAP30: Last Call"
THUSTR_31 = "MAP31: Pharaoh"
THUSTR_32 = "MAP32: Caribbean"

# -----------------------------------------------------------------------------
# FINALE & INTERMISSION TEXTS
# -----------------------------------------------------------------------------

E1TEXT = "ONCE YOU BEAT THE BIG BADASSES AND\nCLEAN OUT THE MOON BASE YOU'RE SUPPOSED\nTO WIN, AREN'T YOU? AREN'T YOU? WHERE'S\nYOUR FAT REWARD AND TICKET HOME? WHAT\nTHE HELL IS THIS? IT'S NOT SUPPOSED TO\nEND THIS WAY!\n\nIT STINKS LIKE ROTTEN MEAT, BUT LOOKS\nLIKE THE LOST DEIMOS BASE.  LOOKS LIKE\nYOU'RE STUCK ON THE SHORES OF HELL.\nTHE ONLY WAY OUT IS THROUGH.\n\nTO CONTINUE THE DOOM EXPERIENCE, PLAY\nTHE SHORES OF HELL AND ITS AMAZING\nSEQUEL, INFERNO!\n"

E2TEXT = "YOU'VE DONE IT! THE HIDEOUS CYBER-\nDEMON LORD THAT RULED THE LOST DEIMOS\nMOON BASE HAS BEEN SLAIN AND YOU\nARE TRIUMPHANT! BUT ... WHERE ARE\nYOU? YOU CLAMBER TO THE EDGE OF THE\nMOON AND LOOK DOWN TO SEE THE AWFUL\nTRUTH.\n\nDEIMOS FLOATS ABOVE HELL ITSELF!\nYOU'VE NEVER HEARD OF ANYONE ESCAPING\nFROM HELL, BUT YOU'LL MAKE THE BASTARDS\nSORRY THEY EVER HEARD OF YOU! QUICKLY,\nYOU RAPPEL DOWN TO  THE SURFACE OF\nHELL.\n\nNOW, IT'S ON TO THE FINAL CHAPTER OF\nDOOM! -- INFERNO.\n"

E3TEXT = "THE LOATHSOME SPIDERDEMON THAT\nMASTERMINDED THE INVASION OF THE MOON\nBASES AND CAUSED SO MUCH DEATH HAS HAD\nITS ASS KICKED FOR ALL TIME.\n\nA HIDDEN DOORWAY OPENS AND YOU ENTER.\nYOU'VE PROVEN TOO TOUGH FOR HELL TO\nCONTAIN, AND NOW HELL AT LAST PLAYS\nFAIR -- FOR YOU EMERGE FROM THE STYGIAN\nDOORS TO SEE THE GREEN FIELDS OF EARTH!\nYOU'RE HOME.\n\nYOU WONDER WHAT'S BEEN HAPPENING ON\nEARTH WHILE YOU WERE BATTLING EVIL\nUNLEASHED. IT'S GOOD THAT NO HELL-\nSPAWN COULD HAVE COME THROUGH THAT\nDOOR WITH YOU ...\n"

E4TEXT = "THE SPIDER MASTERMIND MUST HAVE SENT FORTH\nITS LEGIONS OF HELLSPAWN BEFORE YOUR\nFINAL CONFRONTATION WITH THAT TERRIBLE\nBEAST FROM HELL.  BUT YOU STEPPED FORWARD\nAND BROUGHT FORTH EVERLASTING RETRIBUTION\nAND RUIN TO THAT UNHOLY BINGE OF THE\nUNDERWORLD.\n\nYOU'VE PROVEN ONCE AGAIN THAT YOU ARE NOT\nTO BE PUT TO THE TEST. BUT WHAT LURKS\nAHEAD?  NO TIME TO THINK ABOUT THAT\nNOW ... A GREAT REWARD AWAITS YOU ...\n"

C1TEXT = "YOU HAVE ENTERED DEEPLY INTO THE INFESTED\nSTARPORT. BUT SOMETHING IS WRONG. THE\nMONSTERS HAVE BROUGHT THEIR OWN REALITY\nWITH THEM, AND THE STARPORT'S TECHNOLOGY\nIS BEING SUBVERTED BY THEIR PRESENCE.\n\nAHEAD, YOU SEE AN OUTPOST OF HELL, A\nFORTIFIED ZONE. IF YOU CAN GET PAST IT,\nYOU CAN PENETRATE INTO THE HAUNTED HEART\nOF THE STARBASE AND FIND THE CONTROLLING\nSWITCH WHICH HOLDS EARTH'S POPULATION\nHOSTAGE."

C2TEXT = "YOU HAVE WON! YOUR VICTORY HAS ENABLED\nHUMANKIND TO EVACUATE EARTH AND ESCAPE\nTHE NIGHTMARE.  NOW YOU ARE THE ONLY\nHUMAN LEFT ON THE FACE OF THE PLANET.\nCANNIBAL MUTATIONS, BLOODTHIRSTY FIENDS,\nAND FLESH-EATING SPIRITS ARE YOUR ONLY\nNEIGHBORS. YOU SIT BACK AND WAIT FOR\nDEATH, CONTENT THAT YOU HAVE SAVED YOUR\nSPECIES.\n\nBUT THEN, EARTH CONTROL BEAMS DOWN A\nMESSAGE FROM SPACE: \"SENSORS INDICATE\nALIEN BEINGS ARE ORIGINATING FROM AN\nANOMALY DEEP BENEATH THE STARPORT.\"\nYOU REALIZE THAT THE DEMONS HAVE BROUGHT\nTHEIR OWN REALITY WITH THEM. YOU ARE THE\nONLY DEFENDER LEFT."

C3TEXT = "YOU ARE AT THE CORRUPT HEART OF THE CITY,\nSURROUNDED BY THE CORPSES OF YOUR ENEMIES.\nYOU SEE NO WAY TO DESTROY THE CREATURES'\nPORTAL ON THIS SIDE, SO YOU CLINCH YOUR\nTEETH AND PLUNGE THROUGH IT.\n\nTHERE MUST BE A WAY TO CLOSE IT ON THE\nOTHER SIDE. WHAT DO YOU CARE IF YOU'VE\nGOT TO GO THROUGH HELL TO GET TO IT?"

C4TEXT = "THE HIDEOUS DEMON-SPITTER EXHAUSTS ITS\nFIERY BREATH AND COLLAPSES.\n\nITS LACKING PORTAL OPENS, EXPOSING THE\nBLUE SKY OF EARTH. YOU STRUGGLE THROUGH\nTHE EXIT AND SURVEY THE DEVASTATED\nPLANET.\n\nTHE MONSTERS ARE DEAD. EARTH CAN BE\nREBUILT. YOU MAY BE POUNDED AND BATTERED,\nBUT AT LEAST YOU ARE ALIVE..."

C5TEXT = "CONGRATULATIONS, YOU'VE FOUND THE SECRET\nLEVEL! LOOKS LIKE IT'S BEEN BUILT BY\nHUMANS, RATHER THAN DEMONS. YOU WONDER\nWHO THE INMATES OF THIS PENAL INSTITUTION\nCOULD HAVE BEEN."

C6TEXT = "CONGRATULATIONS, YOU'VE FOUND THE\nSUPER SECRET LEVEL!  YOU'D BETTER\nCLEAR OUT THIS AWE-INSPIRING CASTLE\nAND ITS MYSTERIOUS ARCHITECT."

P1TEXT = "PLUTONIA FINALE 1"
P2TEXT = "PLUTONIA FINALE 2"
P3TEXT = "PLUTONIA FINALE 3"
P4TEXT = "PLUTONIA FINALE 4"
P5TEXT = "PLUTONIA FINALE 5"
P6TEXT = "PLUTONIA FINALE 6"

T1TEXT = "TNT FINALE 1"
T2TEXT = "TNT FINALE 2"
T3TEXT = "TNT FINALE 3"
T4TEXT = "TNT FINALE 4"
T5TEXT = "TNT FINALE 5"
T6TEXT = "TNT FINALE 6"

CC_ZOMBIE = "ZOMBIEMAN"
CC_SHOTGUN = "SHOTGUN GUY"
CC_HEAVY = "HEAVY WEAPON DUDE"
CC_IMP = "IMP"
CC_DEMON = "DEMON"
CC_LOST = "LOST SOUL"
CC_CACO = "CACODEMON"
CC_HELL = "HELL KNIGHT"
CC_BARON = "BARON OF HELL"
CC_ARACH = "ARACHNOTRON"
CC_PAIN = "PAIN ELEMENTAL"
CC_REVEN = "REVENANT"
CC_MANCU = "MANCUBUS"
CC_ARCH = "ARCH-VILE"
CC_SPIDER = "THE SPIDER MASTERMIND"
CC_CYBER = "THE CYBERDEMON"
CC_HERO = "OUR HERO"

HUSTR_CHATMACRO0 = "No"
HUSTR_CHATMACRO1 = "I'm ready to kick butt!"
HUSTR_CHATMACRO2 = "I'm OK."
HUSTR_CHATMACRO3 = "I'm not looking too good!"
HUSTR_CHATMACRO4 = "Help!"
HUSTR_CHATMACRO5 = "You suck!"
HUSTR_CHATMACRO6 = "Next time, scumbag..."
HUSTR_CHATMACRO7 = "Come here!"
HUSTR_CHATMACRO8 = "I'll take care of it."
HUSTR_CHATMACRO9 = "Yes"
